from __future__ import annotations

from anki_enhance_gui.enhancements.enhance_bottom_bar_stats import main as enhance_bottom_bar_stats
from anki_enhance_gui.enhancements.enhance_speed_focus_mode import main as enhance_speed_focus_mode

enhance_bottom_bar_stats()
enhance_speed_focus_mode()
